# Application configuration
server.port=8080

# Spring Documentation Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Use a static OpenAPI file
springdoc.swagger-ui.url=/openapi.yaml 